# File: .github/workflows/main_production-monitor-with-ai-insights.yml
name: Build and deploy Python app to Azure Web App - Production-Monitor-with-AI-Insights

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          
      - name: Install dependencies
        run: |
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create Azure deployment files
        run: |
          # Create startup command file
          echo "python -m streamlit run app.py --server.port=8000 --server.address=0.0.0.0 --server.headless=true" > startup.txt
          
          # Create .deployment file for Azure
          cat > .deployment << EOF
          [config]
          SCM_DO_BUILD_DURING_DEPLOYMENT=true
          EOF
          
          # Create web.config for proper Azure handling
          cat > web.config << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="python" arguments="-m streamlit run app.py --server.port=%HTTP_PLATFORM_PORT% --server.address=0.0.0.0 --server.headless=true" stdoutLogEnabled="true" stdoutLogFile="D:\home\LogFiles\python_stdout.log" startupTimeLimit="60" requestTimeout="00:04:00"/>
            </system.webServer>
          </configuration>
          EOF
          
          # Create oryx build manifest
          cat > oryx-manifest.toml << EOF
          [build]
          virtualenv_name = "antenv"
          packages_dir = "__oryx_packages__"
          
          [python]
          version = "3.10"
          
          [deploy]
          startup_file = "startup.txt"
          EOF
          
          # Create .streamlit directory and config
          mkdir -p .streamlit
          cat > .streamlit/config.toml << EOF
          [server]
          headless = true
          port = 8000
          enableCORS = false
          enableXsrfProtection = false
          
          [browser]
          gatherUsageStats = false
          
          [theme]
          primaryColor = "#1E40AF"
          backgroundColor = "#FFFFFF"
          secondaryBackgroundColor = "#F8FAFC"
          textColor = "#1F2937"
          EOF
          
          # Create secrets template (will be populated by startup script)
          echo 'GOOGLE_API_KEY = ""' > .streamlit/secrets.toml.template

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "__pycache__/*" "*.pyc" "antenv/*" ".venv/*" "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BDD7F062A6445B4A1BF2847D9594321 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F5CFFFD58A04D62BF6480E2CC992765 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60CE04C7D3FB45CEAEEFB79C05F181C7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Production-Monitor-with-AI-Insights'
          slot-name: 'Production'
