# File: .github/workflows/main_production-monitor-with-ai-insights.yml
name: Build and deploy Python app to Azure Web App - Production-Monitor-with-AI-Insights

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zip artifact for deployment
        run: |
          # 只包含必要文件，排除冲突的配置文件
          zip -r release.zip . -x "*.git*" "__pycache__/*" "*.pyc" ".pytest_cache/*" "startup.sh" "web.config" "oryx-manifest.toml"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BDD7F062A6445B4A1BF2847D9594321 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F5CFFFD58A04D62BF6480E2CC992765 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60CE04C7D3FB45CEAEEFB79C05F181C7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Production-Monitor-with-AI-Insights'
          slot-name: 'Production'
